# Configuration Dokploy pour AGRIA Hub - Production
version: "1.0"

project:
  name: "agria-hub"
  description: "Application AGRIA Hub - Gestion agricole moderne"
  domain: "mobile.agriarouen.fr"
  environment: "production"

# Applications
applications:
  frontend:
    name: "agria-frontend"
    type: "static"
    build:
      dockerfile: "Dockerfile.frontend"
      context: "./frontend"
    domain: "mobile.agriarouen.fr"
    port: 8080
    healthcheck:
      path: "/health"
      interval: 30
      timeout: 10
      retries: 3
    resources:
      memory: "512Mi"
      cpu: "0.5"
    env:
      - NODE_ENV=production
      - VITE_API_URL=https://mobile.agriarouen.fr/api
      - VITE_APP_NAME=AGRIA Hub
    
  backend:
    name: "agria-backend"
    type: "php"
    build:
      dockerfile: "Dockerfile.backend"
      context: "./backend"
    port: 9000
    healthcheck:
      path: "/api/health"
      interval: 30
      timeout: 10
      retries: 3
    resources:
      memory: "1Gi"
      cpu: "1"
    env:
      - PHP_ENV=production
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

# Base de données
databases:
  mysql:
    name: "agria-database"
    type: "mysql"
    version: "8.0"
    database: "${DB_NAME}"
    username: "${DB_USER}"
    password: "${DB_PASS}"
    rootPassword: "${DB_ROOT_PASS}"
    resources:
      memory: "1Gi"
      cpu: "0.5"
      storage: "10Gi"
    backup:
      enabled: true
      schedule: "0 2 * * *"
      retention: "7d"

# Redis (optionnel)
redis:
  name: "agria-redis"
  type: "redis"
  version: "7-alpine"
  password: "${REDIS_PASSWORD}"
  resources:
    memory: "256Mi"
    cpu: "0.2"

# Secrets
secrets:
  - name: "db-credentials"
    data:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_ROOT_PASS: "${DB_ROOT_PASS}"
  
  - name: "api-keys"
    data:
      JWT_SECRET: "${JWT_SECRET}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
  
  - name: "smtp-config"
    data:
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASS: "${SMTP_PASS}"

# SSL/TLS
ssl:
  enabled: true
  provider: "letsencrypt"
  email: "${SSL_EMAIL}"
  domains:
    - "mobile.agriarouen.fr"

# Monitoring
monitoring:
  enabled: true
  metrics:
    - cpu
    - memory
    - disk
    - network
  alerts:
    email: "${ADMIN_EMAIL}"
    slack: "${SLACK_WEBHOOK_URL}"

# Backup
backup:
  enabled: true
  schedule: "0 3 * * *"
  retention: "30d"
  storage:
    type: "s3"
    bucket: "${BACKUP_S3_BUCKET}"
    region: "${BACKUP_S3_REGION}"
    accessKey: "${BACKUP_S3_ACCESS_KEY}"
    secretKey: "${BACKUP_S3_SECRET_KEY}"

# Stratégie de déploiement
deployment:
  strategy: "rolling"
  maxUnavailable: 1
  maxSurge: 1
  progressDeadlineSeconds: 600
  
# Scaling
scaling:
  frontend:
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 70
  backend:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 80

# Logs
logging:
  level: "${LOG_LEVEL}"
  retention: "30d"
  aggregation: true